# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1709, 898)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI Light")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setStyleSheet("")
        self.tabWidget.setObjectName("tabWidget")
        self.gen_markers_tab = QtWidgets.QWidget()
        self.gen_markers_tab.setObjectName("gen_markers_tab")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.gen_markers_tab)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame = QtWidgets.QFrame(self.gen_markers_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox.setAutoFillBackground(False)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(120, 0))
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.gen_markers_arucoDict = QtWidgets.QComboBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_markers_arucoDict.sizePolicy().hasHeightForWidth())
        self.gen_markers_arucoDict.setSizePolicy(sizePolicy)
        self.gen_markers_arucoDict.setObjectName("gen_markers_arucoDict")
        self.gridLayout_3.addWidget(self.gen_markers_arucoDict, 0, 1, 1, 1)
        self.gen_markers_dpi = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_markers_dpi.sizePolicy().hasHeightForWidth())
        self.gen_markers_dpi.setSizePolicy(sizePolicy)
        self.gen_markers_dpi.setMaximum(64000)
        self.gen_markers_dpi.setSingleStep(1)
        self.gen_markers_dpi.setProperty("value", 300)
        self.gen_markers_dpi.setObjectName("gen_markers_dpi")
        self.gridLayout_3.addWidget(self.gen_markers_dpi, 3, 1, 1, 1)
        self.gen_markers_save_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_markers_save_btn.sizePolicy().hasHeightForWidth())
        self.gen_markers_save_btn.setSizePolicy(sizePolicy)
        self.gen_markers_save_btn.setMinimumSize(QtCore.QSize(120, 0))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("Resources/icons/diskette.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gen_markers_save_btn.setIcon(icon)
        self.gen_markers_save_btn.setIconSize(QtCore.QSize(30, 30))
        self.gen_markers_save_btn.setObjectName("gen_markers_save_btn")
        self.gridLayout_3.addWidget(self.gen_markers_save_btn, 4, 0, 1, 1)
        self.gen_markers_size = QtWidgets.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_markers_size.sizePolicy().hasHeightForWidth())
        self.gen_markers_size.setSizePolicy(sizePolicy)
        self.gen_markers_size.setSingleStep(0.5)
        self.gen_markers_size.setProperty("value", 10.0)
        self.gen_markers_size.setObjectName("gen_markers_size")
        self.gridLayout_3.addWidget(self.gen_markers_size, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setMinimumSize(QtCore.QSize(120, 0))
        self.label_4.setObjectName("label_4")
        self.gridLayout_3.addWidget(self.label_4, 3, 0, 1, 1)
        self.gen_markers_num = QtWidgets.QSpinBox(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_markers_num.sizePolicy().hasHeightForWidth())
        self.gen_markers_num.setSizePolicy(sizePolicy)
        self.gen_markers_num.setMaximum(50)
        self.gen_markers_num.setProperty("value", 5)
        self.gen_markers_num.setObjectName("gen_markers_num")
        self.gridLayout_3.addWidget(self.gen_markers_num, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMinimumSize(QtCore.QSize(120, 0))
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMinimumSize(QtCore.QSize(120, 0))
        self.label_3.setObjectName("label_3")
        self.gridLayout_3.addWidget(self.label_3, 2, 0, 1, 1)
        self.gen_markers_run_btn = QtWidgets.QPushButton(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_markers_run_btn.sizePolicy().hasHeightForWidth())
        self.gen_markers_run_btn.setSizePolicy(sizePolicy)
        self.gen_markers_run_btn.setLayoutDirection(QtCore.Qt.LeftToRight)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("Resources/icons/qr-code.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gen_markers_run_btn.setIcon(icon1)
        self.gen_markers_run_btn.setIconSize(QtCore.QSize(30, 30))
        self.gen_markers_run_btn.setObjectName("gen_markers_run_btn")
        self.gridLayout_3.addWidget(self.gen_markers_run_btn, 4, 1, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.label_10 = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.verticalLayout.addWidget(self.label_10)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gen_marker_Gview = QtWidgets.QWidget(self.gen_markers_tab)
        self.gen_marker_Gview.setStyleSheet("background-color:rgb(0, 170, 255);\\n")
        self.gen_marker_Gview.setObjectName("gen_marker_Gview")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gen_marker_Gview)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.horizontalLayout_2.addWidget(self.gen_marker_Gview)
        self.tabWidget.addTab(self.gen_markers_tab, "")
        self.gen_board_tab = QtWidgets.QWidget()
        self.gen_board_tab.setObjectName("gen_board_tab")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.gen_board_tab)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.frame_2 = QtWidgets.QFrame(self.gen_board_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_2.sizePolicy().hasHeightForWidth())
        self.groupBox_2.setSizePolicy(sizePolicy)
        self.groupBox_2.setMinimumSize(QtCore.QSize(300, 0))
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.groupBox_2.setAutoFillBackground(False)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.groupBox_2)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 1, 0, 1, 1)
        self.gen_board_scr_w = QtWidgets.QSpinBox(self.groupBox_2)
        self.gen_board_scr_w.setMaximum(1000000)
        self.gen_board_scr_w.setProperty("value", 2560)
        self.gen_board_scr_w.setObjectName("gen_board_scr_w")
        self.gridLayout_2.addWidget(self.gen_board_scr_w, 1, 1, 1, 1)
        self.gen_board_run_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_board_run_btn.sizePolicy().hasHeightForWidth())
        self.gen_board_run_btn.setSizePolicy(sizePolicy)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("Resources/icons/chessboard.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.gen_board_run_btn.setIcon(icon2)
        self.gen_board_run_btn.setIconSize(QtCore.QSize(30, 30))
        self.gen_board_run_btn.setObjectName("gen_board_run_btn")
        self.gridLayout_2.addWidget(self.gen_board_run_btn, 3, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.groupBox_2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_2.addWidget(self.label_9, 2, 0, 1, 1)
        self.gen_board_scr_h = QtWidgets.QSpinBox(self.groupBox_2)
        self.gen_board_scr_h.setMaximum(1000000)
        self.gen_board_scr_h.setProperty("value", 1440)
        self.gen_board_scr_h.setObjectName("gen_board_scr_h")
        self.gridLayout_2.addWidget(self.gen_board_scr_h, 2, 1, 1, 1)
        self.gen_board_save_btn = QtWidgets.QPushButton(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_board_save_btn.sizePolicy().hasHeightForWidth())
        self.gen_board_save_btn.setSizePolicy(sizePolicy)
        self.gen_board_save_btn.setIcon(icon)
        self.gen_board_save_btn.setIconSize(QtCore.QSize(30, 30))
        self.gen_board_save_btn.setObjectName("gen_board_save_btn")
        self.gridLayout_2.addWidget(self.gen_board_save_btn, 3, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.gen_board_arucoDict = QtWidgets.QComboBox(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gen_board_arucoDict.sizePolicy().hasHeightForWidth())
        self.gen_board_arucoDict.setSizePolicy(sizePolicy)
        self.gen_board_arucoDict.setObjectName("gen_board_arucoDict")
        self.gridLayout_2.addWidget(self.gen_board_arucoDict, 0, 1, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_2)
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_3.addWidget(self.frame_2)
        self.gen_board_Gview = QtWidgets.QWidget(self.gen_board_tab)
        self.gen_board_Gview.setStyleSheet("background-color:rgb(0, 170, 255);\\n")
        self.gen_board_Gview.setObjectName("gen_board_Gview")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.gen_board_Gview)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_3.addWidget(self.gen_board_Gview)
        self.tabWidget.addTab(self.gen_board_tab, "")
        self.calibration_tab = QtWidgets.QWidget()
        self.calibration_tab.setObjectName("calibration_tab")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.calibration_tab)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.calibration_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_3.sizePolicy().hasHeightForWidth())
        self.frame_3.setSizePolicy(sizePolicy)
        self.frame_3.setMinimumSize(QtCore.QSize(250, 0))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.groupBox_3 = QtWidgets.QGroupBox(self.frame_3)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_4 = QtWidgets.QFrame(self.groupBox_3)
        self.frame_4.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout.setObjectName("gridLayout")
        self.label_13 = QtWidgets.QLabel(self.frame_4)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 0, 0, 1, 1)
        self.calibrate_aruco_dict = QtWidgets.QComboBox(self.frame_4)
        self.calibrate_aruco_dict.setObjectName("calibrate_aruco_dict")
        self.gridLayout.addWidget(self.calibrate_aruco_dict, 0, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.calibrate_screen_width = QtWidgets.QSpinBox(self.frame_4)
        self.calibrate_screen_width.setMaximum(1000000)
        self.calibrate_screen_width.setProperty("value", 2560)
        self.calibrate_screen_width.setObjectName("calibrate_screen_width")
        self.gridLayout.addWidget(self.calibrate_screen_width, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.calibrate_screem_height = QtWidgets.QSpinBox(self.frame_4)
        self.calibrate_screem_height.setMaximum(1000000)
        self.calibrate_screem_height.setProperty("value", 1440)
        self.calibrate_screem_height.setDisplayIntegerBase(10)
        self.calibrate_screem_height.setObjectName("calibrate_screem_height")
        self.gridLayout.addWidget(self.calibrate_screem_height, 2, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.calibrate_screen_inches = QtWidgets.QDoubleSpinBox(self.frame_4)
        self.calibrate_screen_inches.setDecimals(1)
        self.calibrate_screen_inches.setMaximum(10000.0)
        self.calibrate_screen_inches.setSingleStep(0.1)
        self.calibrate_screen_inches.setProperty("value", 27.0)
        self.calibrate_screen_inches.setObjectName("calibrate_screen_inches")
        self.gridLayout.addWidget(self.calibrate_screen_inches, 3, 1, 1, 1)
        self.calibrate_progress = QtWidgets.QProgressBar(self.frame_4)
        self.calibrate_progress.setProperty("value", 0)
        self.calibrate_progress.setObjectName("calibrate_progress")
        self.gridLayout.addWidget(self.calibrate_progress, 4, 0, 1, 1)
        self.calibrate_start_btn = QtWidgets.QPushButton(self.frame_4)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("Resources/icons/speedometer.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrate_start_btn.setIcon(icon3)
        self.calibrate_start_btn.setObjectName("calibrate_start_btn")
        self.gridLayout.addWidget(self.calibrate_start_btn, 4, 1, 1, 1)
        self.verticalLayout_4.addWidget(self.frame_4)
        self.label_14 = QtWidgets.QLabel(self.groupBox_3)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_4.addWidget(self.label_14)
        self.calibrate_load_photo = QtWidgets.QPushButton(self.groupBox_3)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("Resources/icons/camera.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrate_load_photo.setIcon(icon4)
        self.calibrate_load_photo.setAutoRepeat(False)
        self.calibrate_load_photo.setAutoDefault(True)
        self.calibrate_load_photo.setDefault(False)
        self.calibrate_load_photo.setFlat(False)
        self.calibrate_load_photo.setObjectName("calibrate_load_photo")
        self.verticalLayout_4.addWidget(self.calibrate_load_photo)
        self.calibrate_photo_list = QtWidgets.QListWidget(self.groupBox_3)
        self.calibrate_photo_list.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.calibrate_photo_list.setObjectName("calibrate_photo_list")
        self.verticalLayout_4.addWidget(self.calibrate_photo_list)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.calibrate_load_settings = QtWidgets.QPushButton(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.calibrate_load_settings.sizePolicy().hasHeightForWidth())
        self.calibrate_load_settings.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("Resources/icons/settings.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.calibrate_load_settings.setIcon(icon5)
        self.calibrate_load_settings.setObjectName("calibrate_load_settings")
        self.horizontalLayout_5.addWidget(self.calibrate_load_settings)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.calibrate_save_settings = QtWidgets.QPushButton(self.frame_3)
        self.calibrate_save_settings.setIcon(icon)
        self.calibrate_save_settings.setObjectName("calibrate_save_settings")
        self.horizontalLayout_6.addWidget(self.calibrate_save_settings)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_4.addWidget(self.frame_3)
        self.calibrate_Gview = QtWidgets.QWidget(self.calibration_tab)
        self.calibrate_Gview.setStyleSheet("background-color:rgb(0, 170, 255);\\n")
        self.calibrate_Gview.setObjectName("calibrate_Gview")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.calibrate_Gview)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.horizontalLayout_4.addWidget(self.calibrate_Gview)
        self.tabWidget.addTab(self.calibration_tab, "")
        self.video_tracking_tab = QtWidgets.QWidget()
        self.video_tracking_tab.setObjectName("video_tracking_tab")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.video_tracking_tab)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.frame_5 = QtWidgets.QFrame(self.video_tracking_tab)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.frame_5)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.groupBox_5 = QtWidgets.QGroupBox(self.frame_5)
        self.groupBox_5.setObjectName("groupBox_5")
        self.horizontalLayout_7.addWidget(self.groupBox_5)
        self.video = QVideoWidget(self.frame_5)
        self.video.setStyleSheet("background-color:rgb(0, 170, 255);\\n")
        self.video.setObjectName("video")
        self.horizontalLayout_7.addWidget(self.video)
        self.horizontalLayout_8.addWidget(self.frame_5)
        self.tabWidget.addTab(self.video_tracking_tab, "")
        self.calibration_errors_tab = QtWidgets.QWidget()
        self.calibration_errors_tab.setObjectName("calibration_errors_tab")
        self.tabWidget.addTab(self.calibration_errors_tab, "")
        self.horizontalLayout.addWidget(self.tabWidget)
        self.groupBox_4 = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setMinimumSize(QtCore.QSize(250, 20))
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.groupBox_4)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_18 = QtWidgets.QLabel(self.groupBox_4)
        self.label_18.setObjectName("label_18")
        self.gridLayout_7.addWidget(self.label_18, 1, 2, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.groupBox_4)
        self.label_20.setObjectName("label_20")
        self.gridLayout_7.addWidget(self.label_20, 2, 2, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.groupBox_4)
        self.label_19.setObjectName("label_19")
        self.gridLayout_7.addWidget(self.label_19, 2, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem2, 3, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.groupBox_4)
        self.label_16.setObjectName("label_16")
        self.gridLayout_7.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.groupBox_4)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.line_2 = QtWidgets.QFrame(self.groupBox_4)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_2.setLineWidth(5)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setObjectName("line_2")
        self.gridLayout_7.addWidget(self.line_2, 2, 1, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.groupBox_4)
        self.label_17.setObjectName("label_17")
        self.gridLayout_7.addWidget(self.label_17, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(self.groupBox_4)
        self.line.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line.setLineWidth(5)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setObjectName("line")
        self.gridLayout_7.addWidget(self.line, 0, 1, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.groupBox_4)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.line_3.setLineWidth(5)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setObjectName("line_3")
        self.gridLayout_7.addWidget(self.line_3, 1, 1, 1, 1)
        self.horizontalLayout.addWidget(self.groupBox_4)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1709, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(3)
        self.gen_markers_arucoDict.setCurrentIndex(-1)
        self.gen_board_arucoDict.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.gen_markers_arucoDict, self.gen_markers_num)
        MainWindow.setTabOrder(self.gen_markers_num, self.gen_markers_size)
        MainWindow.setTabOrder(self.gen_markers_size, self.gen_markers_dpi)
        MainWindow.setTabOrder(self.gen_markers_dpi, self.gen_markers_run_btn)
        MainWindow.setTabOrder(self.gen_markers_run_btn, self.gen_markers_save_btn)
        MainWindow.setTabOrder(self.gen_markers_save_btn, self.gen_board_arucoDict)
        MainWindow.setTabOrder(self.gen_board_arucoDict, self.gen_board_scr_w)
        MainWindow.setTabOrder(self.gen_board_scr_w, self.gen_board_scr_h)
        MainWindow.setTabOrder(self.gen_board_scr_h, self.gen_board_run_btn)
        MainWindow.setTabOrder(self.gen_board_run_btn, self.gen_board_save_btn)
        MainWindow.setTabOrder(self.gen_board_save_btn, self.calibrate_aruco_dict)
        MainWindow.setTabOrder(self.calibrate_aruco_dict, self.calibrate_screen_width)
        MainWindow.setTabOrder(self.calibrate_screen_width, self.calibrate_screem_height)
        MainWindow.setTabOrder(self.calibrate_screem_height, self.calibrate_screen_inches)
        MainWindow.setTabOrder(self.calibrate_screen_inches, self.calibrate_start_btn)
        MainWindow.setTabOrder(self.calibrate_start_btn, self.calibrate_load_photo)
        MainWindow.setTabOrder(self.calibrate_load_photo, self.calibrate_load_settings)
        MainWindow.setTabOrder(self.calibrate_load_settings, self.calibrate_save_settings)
        MainWindow.setTabOrder(self.calibrate_save_settings, self.calibrate_photo_list)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Пареметры"))
        self.label.setText(_translate("MainWindow", "*Набор меток"))
        self.gen_markers_save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.label_4.setText(_translate("MainWindow", "*DPI печати принтера"))
        self.label_2.setText(_translate("MainWindow", "*Количество меток"))
        self.label_3.setText(_translate("MainWindow", "*Размер метки, мм"))
        self.gen_markers_run_btn.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_10.setText(_translate("MainWindow", "(*поле обязательное для заполнения)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gen_markers_tab), _translate("MainWindow", "Генерация меток"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Пареметры"))
        self.label_6.setText(_translate("MainWindow", "*Ширина монитора, px"))
        self.gen_board_run_btn.setText(_translate("MainWindow", "Сгенерировать"))
        self.label_9.setText(_translate("MainWindow", "*Высота монитора, px"))
        self.gen_board_save_btn.setText(_translate("MainWindow", "Сохранить"))
        self.label_5.setText(_translate("MainWindow", "*Набор меток"))
        self.label_11.setText(_translate("MainWindow", "(*поле обязательное для заполнения)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.gen_board_tab), _translate("MainWindow", "Генерация доски для калибровки"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Параметры калибровки"))
        self.label_13.setText(_translate("MainWindow", "*Набор меток"))
        self.label_7.setText(_translate("MainWindow", "*Ширина монитора, px"))
        self.label_8.setText(_translate("MainWindow", "*Высота монитора, px"))
        self.label_12.setText(_translate("MainWindow", "*Диагональ монитора в дюймах"))
        self.calibrate_start_btn.setText(_translate("MainWindow", "Откалибровать"))
        self.label_14.setText(_translate("MainWindow", "(*поле обязательное для заполнения)"))
        self.calibrate_load_photo.setText(_translate("MainWindow", "Загрузить фотографии"))
        self.calibrate_load_settings.setText(_translate("MainWindow", "Загрузить настройки калибровки"))
        self.calibrate_save_settings.setText(_translate("MainWindow", "Сохранить настройки калибровки"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibration_tab), _translate("MainWindow", "Калибровка камеры"))
        self.groupBox_5.setTitle(_translate("MainWindow", "GroupBox"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.video_tracking_tab), _translate("MainWindow", "Видеотрекинг"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.calibration_errors_tab), _translate("MainWindow", "Вычисление ошибок калибровки"))
        self.groupBox_4.setTitle(_translate("MainWindow", "Систмема распознавания"))
        self.label_18.setText(_translate("MainWindow", "-"))
        self.label_20.setText(_translate("MainWindow", "-"))
        self.label_19.setText(_translate("MainWindow", "Набор меток:"))
        self.label_16.setText(_translate("MainWindow", "Нет"))
        self.label_15.setText(_translate("MainWindow", "Система откалибрована:"))
        self.label_17.setText(_translate("MainWindow", "Сотношение сторон фотографий:"))
from PyQt5.QtMultimediaWidgets import QVideoWidget
